In [5]:
import pandas as pd
import numpy as np
from numpy import loadtxt
from keras.models import Sequential, load_model
from keras.layers import Dense
from sklearn.model_selection import train_test_split

# Load Data

In [36]:
# load the dataset
dataset = pd.read_csv('../../data/raw/random_playlists_songs.csv')
# Clean and convert dataset to numpy array
#dataset.dropna(inplace=True)
song_features = dataset[['danceability','energy','speechiness','acousticness','instrumentalness','liveness','valence']]
song_features = song_features.to_numpy()
song_information = dataset[['playlist_name', 'track.id', 'track.name']]
print(song_features)
print(song_information.head())

[[0.689  0.632  0.0534 ... 0.363  0.112  0.0869]
 [0.741  0.948  0.0439 ... 0.827  0.103  0.177 ]
 [0.764  0.954  0.0588 ... 0.845  0.102  0.317 ]
 ...
 [0.0643 0.0704 0.039  ... 0.767  0.0886 0.0674]
 [0.497  0.537  0.0487 ... 0.849  0.104  0.146 ]
 [0.23   0.168  0.0481 ... 0.906  0.0967 0.0908]]
   playlist_name                track.id                     track.name
0  Techno Bunker  7Azu6woSBIL0Gwj3Y79bn5                Maybe I'm Wrong
1  Techno Bunker  5tzcReCKuj6qYbQQVS0ehG  Cryptic Speech - Original Mix
2  Techno Bunker  2ULBxi4DNecLbc9u9qUuFc                       The Game
3  Techno Bunker  2ZuiSlPG1f0zkP5lFPxzQL                      Knaldrang
4  Techno Bunker  5k5TtPbBNyTy5F7o0TqKVP                    Hyper World


# Load Neural Network Model

In [37]:
neural_network = load_model('../../models/neural_network.h5')

# Classify songs

In [38]:
cancion = [[0.689,  0.632,  0.0534, 0.0483, 0.363,  0.112,  0.0869]]
prediction=neural_network.predict(cancion) 
song_class=np.round(prediction,0)
print(song_class[0][0])

0.0


In [39]:
def classify(song):    
    prediction=neural_network.predict([list(song)]) 
    song_class=np.round(prediction,0)
    return round(song_class[0][0])

new_playlist = song_information.copy()
for index, row in song_information.iterrows():
    song_class = classify(song_features[index])
    if song_class == 0:
        new_playlist.drop(new_playlist.loc[new_playlist['track.id']==row['track.id']].index,  inplace=True)
        
    else:
        #print('song name included: ', row['track.name'])
        None

    
print(new_playlist)

            playlist_name                track.id  \
69    Sweet Soul Chillout  0wtHjEAzLYYyGuk2WtpGwS   
75    Sweet Soul Chillout  111BQRr9rRMHTn69KamC4Z   
76    Sweet Soul Chillout  3jOwA8XZplvTVsV0SdLWhc   
80    Sweet Soul Chillout  55bvjj1m7GbJwABrsBRx3D   
83    Sweet Soul Chillout  0IUTOvJZ6brXtvMZWipush   
...                   ...                     ...   
4062              Nu-Blue  0Xg38XEeI0xRYODGTuFH55   
4064              Nu-Blue  6pmLL6nZ87l0ztMFi0jjno   
4066              Nu-Blue  2WExnKzXQ0Q304vYN5TOhW   
4073   Ambient Essentials  1i8MaQec4fQXj1enX8ZWF4   
4151   Ambient Essentials  5rlG4Fnws22Ecu6aXctE33   

                                            track.name  
69                                                Easy  
75                                 For Once In My Life  
76                                      Rhythm Of Life  
80                                Just The Way You Are  
83                                     What's Going On  
...                  

# Save Playlist data

In [40]:
new_playlist.to_csv('../../data/processed/group_playlist_songs.csv')